clone_depth: 5

version: "{build}"

environment:
  PLATFORM: x64
  matrix:
    - NODEJS_VERSION: "6"
    - NODEJS_VERSION: "8"
    - NODEJS_VERSION: "10"
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - NODEJS_VERSION: "10"
      JAVA_HOME: C:\Program Files\Java\jdk10

install:
  - set PATH=%JAVA_HOME%\bin;%PATH%
  - ps: Install-Product node $env:NODEJS_VERSION $env:PLATFORM
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - java -version
  - npm test

matrix:
  fast_finish: true

cache:
  - 'node_modules -> .appveyor.yml,package.json,package-lock.json'
