language: node_js

git:
  depth: 5

node_js:
  - "6"
  - "8"
  - "10"

script: npm run test:coveralls

after_success:
  - if [ "$TRAVIS_NODE_VERSION" = "10" ]; then npm run coveralls; fi

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules

notifications:
  email: false
